### ISSUE TITLE
Configure the node opc ua compact server

### ISSUE THREAD

**Issue by smalhao** [BiancoRoyal/node-red-contrib-opcua-server#1]
i noticed that a new node for opc ua came up, namely the node opc ua compact server, i'd like to know if anyone has already used this node, i see that it has a tab to register with Local Discover Server and since i'm working with LDS i like a feedback/example of how this node is configured.

**Comment by biancode** [comment]
@smalhao I tested with a node-opcua LDS and it works for me. It needs a running LDS to register. Examples are to find under Node-RED menu -> Import -> Examples -> ...

**Comment by smalhao** [comment]
I found the examples, but I have some doubts about Address Space, I do not understand how to configure it. 
My situation is as follows:
I have an OPC UA server at ip address 10.6.2.121:49580 and the LDS is installed at ip address 10.6.3.244.
I have to register in lds the OPC UA server and the sensor nodes that I have connected in it. My question is how I program this part in Address Space.
Can you help to configure for this node in opc ua server?

![image](https://user-images.githubusercontent.com/30217459/64535013-735d2d80-d30e-11e9-9eba-ad108d2fa3d8.png)

**Comment by biancode** [comment]
Hi, I'm sorry this is support and not an issue here.
