### ISSUE TITLE
Any user can connect with any password

### ISSUE THREAD

**Issue by kihana** [BiancoRoyal/node-red-contrib-opcua-server#10]
Hello,

I try to allow to establish a connection for a particular user only (e.g. "xxx" see image below). Then I connect via UA Expert with this username and its password. And it's OK the connection was established successfully. Then I try to connect with a username that is not specified in the settings (e.g. "asdf") and any password. And the connection was established successfully too. So it looks like that the connection can be created with any user name and password. It's a bug or maybe some additional action should be done to allow access only for specified users?

The same behaviour when **Allow Anonymous** is on and off.

![image](https://user-images.githubusercontent.com/26021226/146404466-a2ed85dc-3061-4d45-b018-83a99185f9d9.png)

**Comment by biancode** [comment]
Hi, did switch off the anonymous option? Otherwise it allows in a fallback that access, too.

**Comment by kihana** [comment]
Yes, I tried to switch off the anonymous option and the behaviour is the same. I could establish a connection with the wrong username and password.

**Comment by kihana** [comment]
> Hi, did you switch off the anonymous option in security? Otherwise it allows it as a fallback to access, too.

Yes, I tried to switch off the anonymous option and the behaviour is the same. I could establish a connection with the wrong username and password.

**Comment by kihana** [comment]
> Hi, did you switch off the anonymous option in security? Otherwise it allows it as a fallback to access, too.

Yes, I tried to switch off the anonymous option and the behaviour is the same. I could establish a connection with the wrong username and password.

**Comment by biancode** [comment]
Ah I see - it is to implement by the creator of the server itself here by overwriting `choreCompact.coreSecurity.checkUserLogon = () => { ... }`
The default is every time true.

**Comment by biancode** [comment]
you get access to the config of the node by the `node` see the hints in a very new server node with the example code inside - the first lines give you all information about the available objects
