### ISSUE TITLE
Server Certificate has expired

### ISSUE THREAD

**Issue by sniicker** [BiancoRoyal/node-red-contrib-opcua-server#12]
**I'm submitting a ...**  (check one with "x")
   
## Problem
 - ( ) bug report => please search GitHub for a similar issue or PR before submitting
 - (x) unexpected behaviour => please visit the Wiki before

### Information
 **Current behaviour**
 
If i connect to Server for example with UA Expert, i get the message "certificate has expired. Validity from 02.2021 to 02.2022. I think its the day i installed the server node.

![image](https://user-images.githubusercontent.com/67097444/154151713-9a6984c4-e2de-407d-b94b-49a13d4671a2.png)

 **Expected behaviour**
 
 NO ERROR Message and a valid date to >100 Years in future to never get problems. :)
Or a example how to change or generate new certificates.

#### Your Environment
**Please tell us about your environment:**

  * (x) I am using just the Node-RED package and got node-opcua installed with it
  * ( ) I have installed node-opcua global from source (using git clone)
  * ( ) I have installed node-opcua as a global package (using npm i -g) 
  
  * Device :
    - (x)Windows: no support    
    - ( ) macOS: v 
    - ( ) Linux: v 
    - ( ) Raspbian: v 
    - ( ) Other:
         - Name:
         - Version:
   
   * Description of the connecting OPC UA system:
   
     - Name   : UA Expert
     - Version: 1.5.1 331
     - Vendor :
     - Link   : https://
     
* **Node-RED version:** 2.1.3

* **node-red-contrib-opcua-server version:**  0.4.1

* **Node:** (min. 10.x)
   `node --version` =  v12.20.2

Please help & many thanks

**Comment by biancode** [comment]
@sniicker you could set your own certificates instead the demo certs or move/rename the PKI folder and reinstall to get a new cert set. The best is to create your own certs for a long term use.

**Comment by sniicker** [comment]
And how can i create them myself?
