### ISSUE TITLE
Create array of structure

### ISSUE THREAD

**Issue by federicab20** [BiancoRoyal/node-red-contrib-opcua-server#13]
Hello! 
I want to create an array of data structure, in particular I have to create a structure, as shown in the image below, and repeat it for N times. How can I do it with this library? It is necessary to work with 'extensionObject' but how can I implement it? Thank you

![image](https://user-images.githubusercontent.com/72925083/154990597-8fef27c1-ef3b-4300-ad7f-dddbdd0fc006.png)

**Comment by biancode** [comment]
@federicab20 you can start with [this information](https://github.com/node-opcua/node-opcua/tree/master/packages/node-opcua-samples/bin)
