### ISSUE TITLE
**Address Space Script** of OPC UA server with Boolean, String or Datetime #120

### ISSUE THREAD

**Issue by dslgomes** [BiancoRoyal/node-red-contrib-opcua-server#3]
**Address Space Script** of OPC UA server with Boolean, String or Datetime 

Hello, I trying use Address Space Script of OPC UA server with Boolean, String or Datetime but ins`t working. Could you help, what i need to do in code bellow to work?
(with Byte, float, double, Int16,32.... works)

const gsamTopCyc = namespace.addVariable({
  "organizedBy": samFolder,
  "browseName": "TopCyc",
  "nodeId": "ns=1;s=TopCyc",
  "dataType": "Boolean",    <<===
	"value": {
	  "get": function() {
		return new Variant({
		  "dataType": DataType.Boolean,  <<===
		  //"value": enable
		  "value": flexServerInternals.sandboxFlowContext.get("samTopCyc")
		});
	  },
	  "set": function(variant) {
		flexServerInternals.sandboxFlowContext.set(
	"samTopCyc",
		  parseFloat(variant.value)
		);
		return opcua.StatusCodes.Good;
	  }
	}
	});

**Comment by biancode** [comment]
Sorry, did not see this.
