### ISSUE TITLE
Can we have updated version for compact opcua server 

### ISSUE THREAD

**Issue by vaniiplon** [BiancoRoyal/node-red-contrib-opcua-server#45]
### Describe the requested feature

As we need opcua server for production, can we have any updated version.

Thanks in Advance

### Motivation

 updated version for production

**Comment by biancode** [comment]
For production we only support our [plus4nodered](https://plus4nodered.com) OPC UA servers like the very new mutable-server

**Comment by vaniiplon** [comment]
how we get this..already raised quote for contributors version.waiting for reply!!!

**Comment by biancode** [comment]
We sent the answer via e-mail this morning. Did you not receive it?

**Comment by vaniiplon** [comment]
not yet received. mail id: ***@***.*** india pvt limited, India07.02.2024, 17:15, "Klaus Landsdorf" ***@***.***>:
We sent the answer via e-mail this morning. Did you not receive it?

**Comment by biancode** [comment]
I got no e-mail until now. Looks like there is a problem. 

You can go to our website to contact https://plus4nodered.com or just use the support e-mail of plus4nodered.com

**Comment by vaniiplon** [comment]
done..sent an email..

**Comment by vaniiplon** [comment]
I have sent email regarding pus4nodered but not yet received any reply..please send quote for contributors version.
Thanks in regards
vani

**Comment by biancode** [comment]
we are in contact via e-mail

**Comment by vaniiplon** [comment]
sir,Can we call to phone number given in site      13.02.2024, 12:15, "Klaus Landsdorf" ***@***.***>: we are in contact via e-mail—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>  GTW:5 Grid Stability & Modernization: Trends & Developments (Insights about Redispatch 2.0; Electromobility & Power plant optimization in Germany & India) : A Seminar Organized by Stadtwerke Schwabisch Hall, Ing-Buro Abhi Energy & iPLON IndiaDate: 18th June,2021 (Friday)Time: 10:00 AM IST | 06:30 AM CETDuration: 120 minutes plus live Q&ARegister Now: https://register.gotowebinar.com/register/201182455930232075Review Detailed Agenda & Speakers here from the link
