### ISSUE TITLE
How to use "Int32" and "String" as DataType

### ISSUE THREAD

**Issue by MaPaSoTo** [BiancoRoyal/node-red-contrib-opcua-server#46]
### Describe the requested feature

Hello, 
I need a small push to the right direction. In all sample files I see that Double will be used and this worked fin. But if I change it to Int32 the value in OPC-UA will always be empty. What I have done so far:
` const WC01_process_state = namespace.addVariable({
    "organizedBy": wc01,
    "browseName": "process_state",
    "nodeId": "ns=1;s=Isolated_Input11",
    "dataType": "Int32",
    "value": {
      "get": function () {
        return new Variant({
          "dataType": DataType.Integer,
          "value": flexServerInternals.sandboxFlowContext.get("WC01_process_state")
        });
      },
      "set": function (variant) {
        flexServerInternals.sandboxFlowContext.set(
          "WC01_process_state",
          parseInt(variant.value)
        );
        return opcua.StatusCodes.Good;
      }
    }
  });`

But this seems not to work. Also for "Strings" I do not know how to do so?
Is there any tip from your side?

Ty

### Motivation

Not sure

**Comment by biancode** [comment]
for support see https://plus4nodered.com and https://p4nr.com
