### ISSUE TITLE
PLUS for Node-RED (P4NR) - plus4nodered.com

### ISSUE THREAD

**Issue by biancode** [BiancoRoyal/node-red-contrib-opcua-server#47]
This package is now maintained under the PLUS for Node-RED (P4NR) B2B Community Dual License.

We provide a lot new features and a better connectivity, plus 95% code coverage tested state of the OPC UA packages. see [our Website](https://www.iniationware.eu/software/plus-for-node-red)

We invested time since 2022 to provide a very strong and fair licensed B2B Community access to get the very new OPC UA Node-RED package and soon the very new Modbus package and over time more and more like DNP and BACnet.
One Membership that gives you or your team a big PLUS for Node-RED with support, books, documentation and if needed the Member Source Code access.

**Pro Contribution Packages**
https://plus4nodered.com

**B2B Community**
https://p4nr.com

**Books**
https://leanpub.com/p4nr-opcuaclient. - the first 100 get a free Trial code inside the book to test all in our [FlowFuse](https://flowfuse.com/) Playground instance

**Comment by vaniiplon** [comment]
we are trying to contact you but till now did not get any response regarding P4NR
Please provide details how to proceed further

Thanks in advance 
Vani

**Comment by biancode** [comment]
@vnvasireddy I sent you an e-mail now. Maybe the response was seen as junk mail? I sent some in Feb. too

**Comment by vaniiplon** [comment]
yes received..thank you.

But need full details regarding the Editions specified.

![Screenshot from 2024-04-22 15-28-00](https://github.com/BiancoRoyal/node-red-contrib-opcua-server/assets/107458041/8d234807-bc38-49ed-954e-7abb514a585d)

Can you send an E-mail with full details on.

Contributors edition
Starters Edition
Business Edition
Enterprise Edition

And would like to know details about the license for the tool

Thanks in advance,
vani@iplon.in
