### ISSUE TITLE
Do all the post-install script certicates always need to be generated?

### ISSUE THREAD

**Issue by hardillb** [BiancoRoyal/node-red-contrib-opcua-server#52]
### Which node-red-contrib-iiot-opcua version are you using?

1.1.1

### What happened?

Installing this node generates LOTS of certificates, does it really need to create them **all** just for an install, they look to be related to testing.

e.g. it takes over an hour to generate these certificates on a FlowFuse Small instance.

### Server

OPCUA-IIoT-Server Node

### How can this be reproduced?

Install the node

### What did you expect to happen?

Not to spend a HUGE amount of time generating certificates

**Comment by biancode** [comment]
Hi Ben, I'm sorry we do not invest in that package anymore at the moment. See #47, P4NR fixes all points with our very new P4NR OPC UA packages and the mutable server in that package

**Comment by hardillb** [comment]
Ok, but can you answer the question, if they are not required I'll submit a pr to remove them.

This can include an update to the readme to point out this is now deprecated

**Comment by biancode** [comment]
All certs are just to switch to a different type, but min one like the 2048 should be available see https://github.com/BiancoRoyal/node-red-contrib-opcua-server/blob/master/src/core/security.js - and for that it needs a new install process to create just that one
